### ISSUE TITLE
Incorrect use of pioSendPci

### ISSUE THREAD

**Issue by LudovicRousseau** [cryptographix/pcsc-deno#7]
Like in https://github.com/cryptographix/pcsc-deno/issues/6 we have a problem with the size of DWORD.

Another problem is that you hard code the protocol value to 1 (for T=0) in https://github.com/cryptographix/pcsc-deno/blob/master/deno-pcsc-ffi/pcsc-ffi-wrapper.ts#L282
This will NOT work for a T=1 card.

You must use the protocol value returned by [SCardConnect()](https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5) in the `pdwActiveProtocol` parameter.

Here is a patch to be able to send an APDU to a T=1 card on GNU/Linux:
```patch
diff --git a/deno-pcsc-ffi/pcsc-ffi-wrapper.ts b/deno-pcsc-ffi/pcsc-ffi-wrapper.ts
index 54ef493..682a450 100644
--- a/deno-pcsc-ffi/pcsc-ffi-wrapper.ts
+++ b/deno-pcsc-ffi/pcsc-ffi-wrapper.ts
@@ -278,11 +278,11 @@ export function SCardDisconnect(
 }
 
 function prepareTransmit(recvLength: DWORD) {
-  const pioSendPci = new Uint8Array(8);
-  new DataView(pioSendPci.buffer).setUint32(0, 1, true);
-  new DataView(pioSendPci.buffer).setUint32(4, 8, true);
+  const pioSendPci = new Uint8Array(16);
+  new DataView(pioSendPci.buffer).setUint32(0, 2, true);
+  new DataView(pioSendPci.buffer).setUint32(8, 16, true);
 
-  const pioRecvPci = new Uint8Array(8);
+  const pioRecvPci = new Uint8Array(16);
   pioRecvPci.set(pioSendPci);
 
   const recvBuffer = new Uint8Array(recvLength + 2);
```
I had to:
- change the size of `pioSendPci` and `pioRecvPci`
- change the value of the protocol from 1 to 2
- change the 2nd parameter `cbPciLength` value from 8 to 16

**Comment by cryptographix** [comment]
Thanks for the issue. I see that the 32/64 bit "DWORD" issue also occurs here. 

Deno has recently including "static" data imports from DLL, so maybe can use pcsc exports for pioRecv and pioSend.

**Comment by LudovicRousseau** [comment]
It works for me now
