### ISSUE TITLE
Truncated card response

### ISSUE THREAD

**Issue by LudovicRousseau** [cryptographix/pcsc-deno#8]
The receiving buffer size should not be computer from the APDU.
In particular in Case 1 APDU where NO Le is present.

Proposed patch:
```patch
diff --git a/deno-pcsc-ffi/card.ts b/deno-pcsc-ffi/card.ts
index fd7ecd2..9608b94 100644
--- a/deno-pcsc-ffi/card.ts
+++ b/deno-pcsc-ffi/card.ts
@@ -56,7 +56,7 @@ export class FFICard implements Card {
     const response = await native.SCardTransmit(
       this.handle,
       commandBytes,
-      2 + (commandAPDU.le ?? 0),
+      2 + 256,
     );
 
     return ResponseAPDU.from(response);
```

Of course this will not work for extended APDU. 

In my case I used a Case 1 APDU (just CLA, INS, P1 & P2):
```
        const command = CommandAPDU
          .from([ISO7816.CLA.ISO, 0, 0, 0]);
```
And the answer was truncated to 4 bytes. So SW was not set the correct 2 bytes.

**Comment by cryptographix** [comment]
@LudovicRousseau, I've committed an alteration with ```2 + (commandAPDU.le ?? 256)```, since if ```Le``` is set on APDU object, the response should normally obey that, and if not set, use 256. What do you think? What about T=1?

**Comment by LudovicRousseau** [comment]
It works for me now.
